name: My app
on: 
  workflow_dispatch:
jobs:
  first-job:
    name: Unit testing
    runs-on: self-hosted
    steps:
      - name: Welcome msg
        run: echo "My first github action"
      - name: list files
        run: ls -la
      - name: date
        run: echo $(date)
